# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ea4fd34bfbdb7aa0a525971a8812a5079736b9c6fe3089c8f8f3d0acd0edf4b11b1ef53c05874fcb57a46677e23cab5779d334ed51d3be1c8f4cd52738d70c

test:
  secret_key_base: 55ac8b0d8b3dc10740c2421ec408bcd308e631365bbbdbcce1c0b32a50804fda2244c2fc182d8fdd6127c2f65c16be4f57340c40fe02ccc8c6ead6bfc94f8bf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
